# Generated by Django 4.0.5 on 2022-06-25 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='relationship',
            field=models.TextField(choices=[('', 'None'), ('single', 'Single'), ('relationship', 'In a relationship'), ('married', 'Married'), ('engaged', 'Engaged')], default='', verbose_name='relationship'),
        ),
        migrations.AddField(
            model_name='profile',
            name='working_at',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
