# Generated by Django 4.0.5 on 2022-06-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='relationship',
            field=models.TextField(blank=True, choices=[('', 'None'), ('single', 'Single'), ('relationship', 'In a relationship'), ('married', 'Married'), ('engaged', 'Engaged')], default='', verbose_name='relationship'),
        ),
    ]
